CREATE DATABASE [Identity]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Identity', FILENAME = N'C:\DB\Databases\Identity.mdf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Identity_log', FILENAME = N'C:\DB\DatabaseLogs\Identity_log.ldf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [Identity] SET COMPATIBILITY_LEVEL = 150
GO
ALTER DATABASE [Identity] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Identity] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Identity] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Identity] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Identity] SET ARITHABORT OFF 
GO
ALTER DATABASE [Identity] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Identity] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Identity] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [Identity] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Identity] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Identity] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Identity] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Identity] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Identity] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Identity] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Identity] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Identity] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Identity] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Identity] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Identity] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Identity] SET  READ_WRITE 
GO
ALTER DATABASE [Identity] SET RECOVERY FULL 
GO
ALTER DATABASE [Identity] SET  MULTI_USER 
GO
ALTER DATABASE [Identity] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Identity] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Identity] SET DELAYED_DURABILITY = DISABLED 
GO
USE [Identity]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = On;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = Primary;
GO
USE [Identity]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [Identity] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
